name: Subgraph CI/CD

on:
  pull_request:
    branches: [main]
    paths: ['pop-subgraph/**']
  push:
    branches: [main]
    paths: ['pop-subgraph/**']

jobs:
  subgraph-sepolia:
    uses: BreadchainCoop/subgraphform/.github/workflows/_subgraph-cicd.yml@main
    with:
      subgraph-name: poa-sepolia
      working-directory: pop-subgraph
      network: sepolia
    secrets:
      GRAPH_DEPLOY_KEY: ${{ secrets.GRAPH_DEPLOY_KEY }}

  subgraph-base-sepolia:
    uses: BreadchainCoop/subgraphform/.github/workflows/_subgraph-cicd.yml@main
    with:
      subgraph-name: poa-base-sepolia
      working-directory: pop-subgraph
      network: base-sepolia
      run-tests: false
    secrets:
      GRAPH_DEPLOY_KEY: ${{ secrets.GRAPH_DEPLOY_KEY }}
